[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npx serve -s dist"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"
PORT = "3000"
VITE_API_URL = "${RAILWAY_PUBLIC_DOMAIN}"
VITE_API_TIMEOUT = "30000"
NPM_CONFIG_PRODUCTION = "true"