[build]
builder = "nixpacks"

[[services]]
name = "frontend"
source.path = "frontend"
env = { NODE_ENV = "production" }

[services.build]
dockerfilePath = "./frontend/Dockerfile"
buildCommand = "npm ci && npm run build"

[[services]]
name = "backend"
source.path = "backend"
env = { NODE_ENV = "production" }

[services.domains]
primary = { name = "api", type = "PRIMARY" }

[deploy]
numReplicas = 1
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10