[build]
builder = "nixpacks"
buildCommand = "npm ci"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"
PORT = "4000"
CORS_ENABLED = "true"
ALLOWED_ORIGINS = "https://va-crm-frontend-production.up.railway.app,https://va-crm-production.up.railway.app"
RAILWAY_PUBLIC_DOMAIN = "${RAILWAY_PUBLIC_DOMAIN}"
DATABASE_URL = "${DATABASE_URL}"
JWT_SECRET = "${JWT_SECRET}"
UPLOAD_DIR = "/tmp/uploads"
MAX_FILE_SIZE = "10485760" # 10MB in bytes

# Logging configuration
LOG_LEVEL = "info"
LOG_FORMAT = "json"

# Monitoring configuration
METRICS_AUTH = "${METRICS_AUTH}"
ENABLE_METRICS = "true"
METRICS_PORT = "9090"

# APM configuration
NEW_RELIC_LICENSE_KEY = "${NEW_RELIC_LICENSE_KEY}"
NEW_RELIC_APP_NAME = "va-crm-backend"

[[services.ports]]
port = 4000
handlers = ["http"]
force_https = true

[services.concurrency]
type = "connections"
hard_limit = 250
soft_limit = 200